# Generated by Django 3.0.5 on 2021-08-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('quantity', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('veg', 'vegetarian'), ('non-veg', 'non-vegetarian')], default='veg', max_length=40)),
                ('image', models.ImageField(upload_to='meida')),
            ],
        ),
    ]
